import type { OrgSettings, SearchFilters } from "./types";
export const NICHES = [
  "Restaurantes",
  "Pizzarias",
  "Hamburguerias",
  "Academias",
  "Clínicas",
  "Clínicas odontológicas",
  "Psicólogos",
  "Fisioterapeutas",
  "Nutricionistas",
  "Advogados",
  "Barbearias",
  "Salões de beleza",
  "Estéticas",
  "Pet shops",
  "Veterinários",
  "Oficinas",
  "Autoelétricas",
  "Lojas de roupas",
  "Imobiliárias",
  "Escolas",
  "Cursos",
  "Hotéis",
  "Pousadas",
  "Contabilidades",
  "Assistências técnicas",
  "Mercados",
  "Farmácias",
  "Empresas de construção",
  "Prestadores de serviços",
];
export const STATES = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
];
export const STAGES = [
  "Descoberto",
  "Analisado",
  "Contato pendente",
  "Contato realizado",
  "Respondeu",
  "Interessado",
  "Proposta enviada",
  "Negociação",
  "Fechado",
  "Perdido",
];
export const CHANNELS = [
  "WhatsApp",
  "Instagram DM",
  "Ligação",
  "E-mail",
  "Visita presencial",
] as const;
export const WEBSITE_LABELS = {
  not_identified: "Site não identificado",
  inconclusive: "Análise inconclusiva",
  social_only: "Somente redes sociais",
  aggregator: "Agregador de links",
  directory: "Página em diretório",
  own_website: "Site próprio identificado",
  unavailable: "Site indisponível",
  needs_improvement: "Site com pontos de melhoria",
};
export const DEFAULT_FILTERS: SearchFilters = {
  country: "Brasil",
  state: "CE",
  city: "Fortaleza",
  neighborhood: "",
  postal_code: "",
  radius: 10,
  category: "Clínicas odontológicas",
  sub_category: "",
  query: "",
  provider: "mock",
  prioritize_no_site: true,
  website_filter: "all",
  min_rating: 0,
  min_reviews: 0,
  min_score: 0,
  has_phone: false,
  has_whatsapp: false,
  crm_status: "all",
  sort: "score",
};
export const DEFAULT_SETTINGS: OrgSettings = {
  provider: "mock",
  sender_name: "",
  agency_name: "Meu estúdio",
  proposal_price: 2500,
  currency: "BRL",
  onboarded: false,
  score_weights: {
    gap: 25,
    reviews: 20,
    rating: 15,
    whatsapp: 10,
    social: 10,
    complete: 8,
    segment: 6,
    activity: 6,
  },
  credit_costs: {
    search: 1,
    enrich: 1,
    audit: 2,
    website: 10,
    regenerate: 3,
    script: 1,
    proposal: 2,
  },
  unit_costs: { osm: 0, mock: 0, licensed: 0, gemini: 0, audit: 0 },
};
export const OBJECTIONS = [
  "Já uso Instagram.",
  "Não preciso de site.",
  "Está caro.",
  "Tenho pouco movimento.",
  "Meu sobrinho faz.",
  "Já tenho alguém cuidando.",
  "Não tenho interesse agora.",
  "Como você conseguiu meu contato?",
  "Vou pensar.",
];
export const EXPORT_FIELDS = [
  "business_name",
  "category",
  "city",
  "state",
  "neighborhood",
  "postal_code",
  "address",
  "phone",
  "public_whatsapp",
  "website",
  "website_status",
  "instagram",
  "facebook",
  "rating",
  "reviews_count",
  "lead_score",
  "lead_status",
  "source",
  "is_demo",
  "last_checked_at",
] as const;
