-- The backend has no administrative tenant bypass. Every private operation
-- requires a verified Auth session and membership. Global cache/counters contain
-- only provider coordination state and remain inaccessible to the Data API.
DROP POLICY backend_access ON public."audit_logs";
CREATE POLICY backend_access ON public."audit_logs" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."business_sources";
CREATE POLICY backend_access ON public."business_sources" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."businesses";
CREATE POLICY backend_access ON public."businesses" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."caches";
CREATE POLICY backend_access ON public."caches" FOR ALL TO orbit_backend USING ((organization_id IS NULL OR private.is_member(organization_id))) WITH CHECK ((organization_id IS NULL OR private.is_member(organization_id)));
DROP POLICY backend_access ON public."credit_transactions";
CREATE POLICY backend_access ON public."credit_transactions" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."crm_activities";
CREATE POLICY backend_access ON public."crm_activities" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."crm_stages";
CREATE POLICY backend_access ON public."crm_stages" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."digital_presences";
CREATE POLICY backend_access ON public."digital_presences" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."generated_websites";
CREATE POLICY backend_access ON public."generated_websites" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."jobs";
CREATE POLICY backend_access ON public."jobs" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."lead_lists";
CREATE POLICY backend_access ON public."lead_lists" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."lead_tag_links";
CREATE POLICY backend_access ON public."lead_tag_links" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."lead_tags";
CREATE POLICY backend_access ON public."lead_tags" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."leads";
CREATE POLICY backend_access ON public."leads" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."locations";
CREATE POLICY backend_access ON public."locations" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."memberships";
CREATE POLICY backend_access ON public."memberships" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."monitors";
CREATE POLICY backend_access ON public."monitors" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."organizations";
CREATE POLICY backend_access ON public."organizations" FOR ALL TO orbit_backend USING ((private.owns_org(id) OR private.is_member(id))) WITH CHECK ((private.owns_org(id) OR private.is_member(id)));
DROP POLICY backend_access ON public."proposals";
CREATE POLICY backend_access ON public."proposals" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."provider_usage";
CREATE POLICY backend_access ON public."provider_usage" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."rate_limits";
CREATE POLICY backend_access ON public."rate_limits" FOR ALL TO orbit_backend USING ((true)) WITH CHECK ((true));
DROP POLICY backend_access ON public."sales_scripts";
CREATE POLICY backend_access ON public."sales_scripts" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."search_results";
CREATE POLICY backend_access ON public."search_results" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."searches";
CREATE POLICY backend_access ON public."searches" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."subscriptions";
CREATE POLICY backend_access ON public."subscriptions" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."users";
CREATE POLICY backend_access ON public."users" FOR ALL TO orbit_backend USING ((auth_user_id=(select auth.uid()) AND (select private.session_valid()))) WITH CHECK ((auth_user_id=(select auth.uid()) AND (select private.session_valid())));
DROP POLICY backend_access ON public."website_analyses";
CREATE POLICY backend_access ON public."website_analyses" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."website_versions";
CREATE POLICY backend_access ON public."website_versions" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));
DROP POLICY backend_access ON public."api_operations";
CREATE POLICY backend_access ON public."api_operations" FOR ALL TO orbit_backend USING ((private.is_member(organization_id))) WITH CHECK ((private.is_member(organization_id)));

CREATE INDEX audit_logs_user_idx ON public.audit_logs (user_id);
CREATE INDEX businesses_location_idx ON public.businesses (organization_id,location_id);
CREATE INDEX caches_org_idx ON public.caches (organization_id);
CREATE INDEX crm_activities_business_idx ON public.crm_activities (organization_id,business_id);
CREATE INDEX crm_activities_user_idx ON public.crm_activities (user_id);
CREATE INDEX generated_websites_business_idx ON public.generated_websites (organization_id,business_id);
CREATE INDEX lead_tag_links_lead_idx ON public.lead_tag_links (organization_id,lead_id);
CREATE INDEX leads_stage_idx ON public.leads (organization_id,stage_id);
CREATE INDEX proposals_business_idx ON public.proposals (organization_id,business_id);
CREATE INDEX sales_scripts_business_idx ON public.sales_scripts (organization_id,business_id);
CREATE INDEX search_results_search_idx ON public.search_results (organization_id,search_id);
CREATE INDEX website_versions_website_idx ON public.website_versions (organization_id,website_id);
